[package]
name = "pherrous-sys"
description = "Low-level bindings to PHP's C API."
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]

[features]
default = []
embed = []

[build-dependencies]
anyhow = "1.0.93"
which = "7.0.0"
